services:
  eureka-server:
    build:
      context: ./eurekaServer
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app_network
    healthcheck:
      test: curl --fail http://localhost:8761/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      EUREKA_SERVER: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      eureka-server:
        condition: service_healthy
    links:
      - eureka-server
    networks:
      - app_network

  email-service:
    build:
      context: ./emailService
      dockerfile: Dockerfile
    container_name: email-service
    ports:
      - "8091:8091"
    environment:
      EUREKA_SERVER: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - focus-service
    network_mode: "host"

  focus-service:
    build:
      context: ./focusService
      dockerfile: Dockerfile
    container_name: focus-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/focus_v1
      SPRING_DATASOURCE_USERNAME: karththi
      SPRING_DATASOURCE_PASSWORD: example-password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      EUREKA_SERVER: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - api-gateway
    network_mode: "host"

networks:
  app_network:
    driver: bridge