server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.49
    renewal-threshold-update-interval-ms: 30000
    expected-response-time-ms: 1000

spring:
  application:
    name: EUREKA-SERVER

# management:
#   metrics:
#     binders:
#       process:
#         enabled: false  # Correct way to disable process metrics