server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: focus-service
          uri: lb://FOCUS-SERVICE
          predicates:
            - Path=/FOCUS-SERVICE/**
          filters:
            - RewritePath=/FOCUS-SERVICE/(?<remaining>.*), /$\{remaining}








