spring:
  application:
    name: EMAIL-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: "eimskyruleengine@gmail.com"
    password: "fcmq sfrj lkfb mria"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9093

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-server:8761/eureka/
