name: Java CI Pipeline

on:
  push:
    branches:
      - main  # Run this on any push to the 'main' branch
  pull_request:
    branches:
      - main  # Run on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - apiGateway
          - focusService
          - eurekaServer

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (adjust version if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Navigate to the service directory and run the Maven build
      - name: Build with Maven
        run: |
          cd ${{ matrix.service }}
          mvn clean install

      # Run tests
      - name: Run tests
        run: |
          cd ${{ matrix.service }}
          mvn test


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
