jobs:
  eureka:
    runs-on: ubuntu-latest
    steps:
      # Existing steps for eureka-server...

  gateway:
    runs-on: ubuntu-latest
    needs: eureka
    steps:
      # Existing steps for gateway...

  focus:
    runs-on: ubuntu-latest
    needs: gateway
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: focus_v1
          MYSQL_ROOT_PASSWORD: example-password
          MYSQL_USER: karththi
          MYSQL_PASSWORD: example-password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=example-password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      # Existing steps for focus-service...

  email:
    runs-on: ubuntu-latest
    needs: focus
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build emailService
        run: |
          cd emailService
          mvn clean install

      - name: Run tests for emailService
        env:
          SPRING_MAIL_HOST: smtp.gmail.com
          SPRING_MAIL_PORT: 587
          SPRING_MAIL_USERNAME: eimskyruleengine@gmail.com
          SPRING_MAIL_PASSWORD: fcmq sfrj lkfb mria
          SPRING_PROFILES_ACTIVE: test
        run: |
          cd emailService
          mvn test
