name: Java CI Pipeline

on:
  push:
    branches:
      - main  # Run this on any push to the 'main' branch
  pull_request:
    branches:
      - main  # Run on pull requests to 'main'

jobs:
  build-eureka:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (adjust version if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build Eureka service
      - name: Build Eureka Server
        run: |
          cd eurekaServer
          mvn clean install

      # Run tests for Eureka service
      - name: Run tests for Eureka Server
        run: |
          cd eurekaServer
          mvn test


  build-gateway:
    runs-on: ubuntu-latest
    needs: build-eureka  # This job will only run if the build-eureka job completes successfully

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (adjust version if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build Gateway service
      - name: Build Gateway
        run: |
          cd gateway
          mvn clean install

      # Run tests for Gateway service
      - name: Run tests for Gateway
        run: |
          cd gateway
          mvn test


  build-focus:
    runs-on: ubuntu-latest
    needs: build-gateway  # This job will only run if the build-gateway job completes successfully

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (adjust version if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build Focus Service
      - name: Build Focus Service
        run: |
          cd focusService
          mvn clean install

      # Run tests for Focus Service
      - name: Run tests for Focus Service
        run: |
          cd focusService
          mvn test
